### ISSUE TITLE
[Python 3] Fix syntax changes

### ISSUE THREAD

**Issue by sigmavirus24** [sqlobject/sqlobject#3]
- [x] Print statements (See #4)
- [x] Raising of exceptions (e.g., `raise ExceptionClass, msg`) (See #6)
- [x] except statements (e.g., `except ExceptionClass, e`) (See #7)
- [ ] Use of Longs (e.g., `1L`)
- [ ] Fix import statements. Implicit local imports are no longer valid. For example

    ```py
    # old sqlobject/__init__.py
    """SQLObject"""
    from __version__ import version, version_info

    from col import *
    from index import *
    from joins import *
    from main import *
    from sqlbuilder import AND, OR, NOT, IN, LIKE, RLIKE, DESC, CONTAINSSTRING, const, func
    from styles import *
    from dbconnection import connectionForURI
    import dberrors

    # new
    """SQLObject"""
    from .__version__ import version, version_info  # Might actually be invalid syntax.

    from .col import *
    from .index import *
    from .joins import *
    from .main import *
    from .sqlbuilder import AND, OR, NOT, IN, LIKE, RLIKE, DESC, CONTAINSSTRING, const, func
    from .styles import *
    from .dbconnection import connectionForURI
    from . import dberrors
    ```

We should ensure that print statements are no longer allowed by the interpreter using `from __future__ import print_function`. I wish we had ways of making the interpreter enforce the others.
